#!/bin/bash
#downloader expects an ENA formatted table of reads section, so please notice that it can handle mainly that kind of data structure

OPTIND=1


table=''
column=10
first_row=2
output_directory="$HOME/data/fastqs"
mode='single'
samples_string=''


while getopts ":f:c:r:d:m:s:" opt; do
	case $opt in
		f)
			table=$OPTARG
			;;
		c)
			column=$OPTARG
			;;
		r)
			first_row=$OPTARG
			;;
		d)
			output_directory=$OPTARG
			;;
	
		m)
			mode=$OPTARG
			;;
		s)
			samples_string=$OPTARG	
	esac
done

mkdir -p $output_directory


if [ -n $samples_string ]
	then
		IFS='_' read -a conditions <<< $samples_string
		IFS=':' read -a n_samples <<< ${conditions[0]}
		IFS=':' read -a conds <<< ${conditions[1]}
fi

if [ $mode = single ]
	then
		for row in $(cut -f $column $table | tail +$first_row); do
			wget -q -P $output_directory $row
			done
		cd $output_directory
		files=(*)
		ind=0
		for i in ${!n_samples[@]}; do for ((n=1; n<=${n_samples[i]}; n++)); do temp=${files[ind]}; mv $temp "${temp%%.*}_${conds[i]}$n.fastq.gz"; ind=$ind+1; done; done	
elif [ $mode = paired ]
	then
		for j in 1 2; do
			for row in $(cut -f $column $table | cut -f $j -d ";" -s); do
				wget -q -P $output_directory $row
				done
			for i in ${!n_samples[@]}; do for ((n=1; n<=${n_samples[i]}; n++)); do temp=${files[ind]}; mv $temp "${temp%%.*}_${conds[i]}$n.fastq.gz"; ind=$ind+1; done; done
			done
else
	echo 'Error, modes can only be "single" or "paired"' 1>&2 
	exit 1
fi


